export enum PokemonTypes {
  Water = 'Water',
  Fire = 'Fire',
  Dragon = 'Dragon',
  Fairy = 'Fairy',
  Ice = 'Ice',
  Ground = 'Ground',
  Rock = 'Rock',
  Psychic = 'Psychic',
  Fighting = 'Fighting',
  Flying = 'Flying',
  Ghost = 'Ghost',
  Steel = 'Steel',
  Dark = 'Dark',
  Normal = 'Normal',
  Grass = 'Grass',
  Electric = 'Electric',
  Poison = 'Poison',
  Bug = 'Bug'
} 