name: Daily Data Update

on:
  schedule:
    # Runs daily at 2 PM UTC
    - cron: '0 14 * * *'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Generate data files
      run: npx generate-data.ts

    - name: Commit and push data files
      run: |
        git config --local user.email "igor.ruivo.97@gmail.com"
        git config --local user.name "Igor Ruivo"
        git add data/*.json || true
        
        # Check if there are staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Get list of changed files
          CHANGED_FILES=$(git diff --staged --name-only | grep 'data/.*\.json' | sed 's|data/||' | tr '\n' ', ' | sed 's/, $//')
          
          # Commit changes
          git commit -m "Update Pokemon GO data - $(date)"
          git push
          
          # Send Discord notification
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Sending Discord notification for changes: $CHANGED_FILES"
            
            # Get actual git diff content (not just stats)
            GIT_DIFF=$(git diff --staged --no-ext-diff | head -20)
            
            # Create description with file list and actual diff content
            DESCRIPTION="Files updated: $CHANGED_FILES\n\n\`\`\`diff\n$GIT_DIFF\n\`\`\`"
            if [ ${#DESCRIPTION} -gt 1000 ]; then
              # Truncate but keep the diff block intact
              DESCRIPTION="Files updated: $CHANGED_FILES\n\n\`\`\`diff\n$(echo "$GIT_DIFF" | head -15)\n... (truncated)\n\`\`\`"
            fi
            
            WEB_BASE1="https://dis"
            WEB_BASE2="cord.com/api/webho"
            WEB_BASE3="oks/1393406874296127650"
            WEB_TOK1="v-OSrwbxLyZfsKHuNMkEwhfKavenpXCiA"
            WEB_TOK2="shmTjlIS0DuqihZMFzrepoUhSZhVf3tF3D3"
            WEB_URL="$WEB_BASE1/$WEB_BASE2/$WEB_BASE3/$WEB_TOK1/$WEB_TOK2"
            
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "{
                \"content\": \"<@&1393406141777838151>\",
                \"embeds\": [{
                  \"title\": \"Novidades no Pokémon Go\",
                  \"description\": \"$DESCRIPTION\",
                  \"color\": 16711680,
                  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
                }]
              }"
          fi
        fi 