name: Daily Data Update

on:
  schedule:
    # Runs daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger data update
      run: |
        VERCEL_URL="https://dex-server.vercel.app"
        curl -X POST $VERCEL_URL/api/trigger
        echo "Data update triggered successfully"